{{-- SPDX-License-Identifier: NCSA --}}
@extends('layouts.public')
@section('content')
<section class="corporate-hero"><div class="container corporate-hero-grid">
  <div class="corporate-hero-copy"><span class="eyebrow">{{ $site['site_name'] }}</span><h1>Mengenal lebih dekat.<br><em>Melangkah bersama.</em></h1><p>{{ $site['site_description'] === '[ISI DESKRIPSI]' ? 'Kenali organisasi kami, ikuti kegiatan komunitas, dan temukan ruang untuk bekerja sama.' : $site['site_description'] }}</p><div class="action-row"><a href="{{ $baseUrl }}/tentang/organisasi" role="button">Kenali organisasi kami</a><a class="text-link" href="{{ $baseUrl }}/kontak">Hubungi kami &rarr;</a></div></div>
  <figure class="corporate-hero-photo"><img src="{{ $baseUrl }}/assets/images/hero-team-collaboration.jpg" width="720" height="720" alt="Ilustrasi kolaborasi dalam lingkungan kerja" fetchpriority="high"><figcaption>Organisasi &amp; komunitas</figcaption></figure>
</div></section>
<nav class="container shortcut-bar" aria-label="Akses cepat">
@foreach([['Profil organisasi','/tentang/organisasi'],['Laporan keuangan','/tentang/laporan-keuangan'],['Project & kegiatan','/project'],['Kerja sama','/kerja-sama']] as [$label,$path])<a href="{{ $baseUrl }}{{ $path }}"><span>{{ $label }}</span><span aria-hidden="true">&rarr;</span></a>@endforeach
</nav>
<section class="section"><div class="container editorial-intro"><div><span class="eyebrow">Tentang kami</span><h2>Kenali arah,<br>orang, dan aktivitas kami.</h2></div><div><p class="lead">Setiap organisasi memiliki cerita dan tujuan. Temukan profil, struktur, serta kegiatan kami di sini.</p><a class="text-link" href="{{ $baseUrl }}/tentang">Tentang organisasi &rarr;</a></div></div></section>
<section class="section section-muted"><div class="container"><div class="section-heading"><div><span class="eyebrow">Jelajahi</span><h2>Terhubung dengan kegiatan kami</h2></div></div><div class="feature-grid">
  <a class="feature-story" href="{{ $baseUrl }}/komunitas"><img src="{{ $baseUrl }}/assets/images/hero-team-collaboration.jpg" width="720" height="720" loading="lazy" alt=""><div><span>Komunitas</span><h3>Ide, cerita, dan ruang untuk berkolaborasi.</h3><span>Jelajahi komunitas &rarr;</span></div></a>
  <div class="feature-directory">@foreach([['01','Organisasi','Profil, sejarah, visi, dan misi organisasi.','/tentang/organisasi'],['02','Kerja Sama','Kenali partner dan inisiatif bersama.','/kerja-sama'],['03','Project','Ikuti kegiatan dan status pelaksanaannya.','/project']] as [$number,$label,$copy,$path])<a href="{{ $baseUrl }}{{ $path }}"><span class="directory-number">{{ $number }}</span><div><h3>{{ $label }}</h3><p>{{ $copy }}</p></div><span aria-hidden="true">&rarr;</span></a>@endforeach</div>
</div></div></section>
<section class="section"><div class="container"><div class="section-heading"><div><span class="eyebrow">Kabar terbaru</span><h2>Informasi &amp; cerita</h2></div><a class="text-link" href="{{ $baseUrl }}/artikel">Semua artikel &rarr;</a></div><div class="article-grid">
@forelse($articles as $article)<article class="article-card">@if($article->thumbnail_url)<img class="article-thumb" src="{{ $article->thumbnail_url }}" alt="" loading="lazy">@endif<div class="article-meta"><time>{{ $article->published_at?->format('d M Y') }}</time><span>{{ number_format($article->views_count) }} klik</span></div><h3><a href="{{ $baseUrl }}/artikel/{{ rawurlencode($article->slug) }}">{{ $article->title }}</a></h3><p>{{ $article->excerpt }}</p><footer><small>{{ $article->author?->name }}</small><a class="text-link" href="{{ $baseUrl }}/artikel/{{ rawurlencode($article->slug) }}">Baca selengkapnya &rarr;</a></footer></article>
@empty<div class="publication-empty"><span class="eyebrow">Publikasi</span><h3>Cerita berikutnya hadir di sini.</h3><p>Belum ada artikel yang diterbitkan. Sementara itu, kenali organisasi dan kegiatan kami.</p><a class="text-link" href="{{ $baseUrl }}/tentang/organisasi">Lihat profil organisasi &rarr;</a></div>@endforelse
</div></div></section>
<section class="investor-feature"><div class="container editorial-intro"><div><span class="eyebrow">Hubungan investor</span><h2>Akses informasi.<br>Pahami perkembangannya.</h2><p>Profil organisasi, laporan keuangan, dan informasi publik dalam satu tempat.</p></div><div class="investor-links"><a href="{{ $baseUrl }}/tentang/laporan-keuangan">Laporan keuangan <span>&rarr;</span></a><a href="{{ $baseUrl }}/hubungan-investor">Informasi investor <span>&rarr;</span></a><a href="{{ $baseUrl }}/kontak">Hubungi organisasi <span>&rarr;</span></a></div></div></section>
@include('partials.corporate-contact')
@endsection
